#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/nokogiri/css/parser.y".
#

require 'racc/parser'


module Nokogiri

  module CSS

    class GeneratedParser < Racc::Parser

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 4, 46, :_reduce_1,
 1, 46, :_reduce_2,
 2, 49, :_reduce_3,
 2, 49, :_reduce_4,
 2, 49, :_reduce_5,
 1, 49, :_reduce_6,
 2, 49, :_reduce_7,
 2, 49, :_reduce_8,
 2, 50, :_reduce_9,
 3, 50, :_reduce_10,
 2, 50, :_reduce_11,
 1, 50, :_reduce_none,
 2, 50, :_reduce_13,
 2, 50, :_reduce_14,
 1, 50, :_reduce_15,
 3, 48, :_reduce_16,
 1, 48, :_reduce_none,
 2, 57, :_reduce_18,
 1, 51, :_reduce_19,
 1, 51, :_reduce_20,
 6, 56, :_reduce_21,
 6, 56, :_reduce_22,
 5, 56, :_reduce_23,
 2, 55, :_reduce_24,
 3, 55, :_reduce_25,
 3, 55, :_reduce_26,
 3, 55, :_reduce_27,
 1, 59, :_reduce_none,
 1, 59, :_reduce_none,
 4, 60, :_reduce_30,
 3, 60, :_reduce_31,
 2, 60, :_reduce_32,
 1, 60, :_reduce_33,
 2, 61, :_reduce_34,
 2, 61, :_reduce_35,
 1, 52, :_reduce_none,
 0, 52, :_reduce_none,
 2, 53, :_reduce_38,
 2, 53, :_reduce_39,
 2, 53, :_reduce_40,
 2, 53, :_reduce_41,
 1, 53, :_reduce_none,
 1, 53, :_reduce_none,
 1, 53, :_reduce_none,
 1, 53, :_reduce_none,
 1, 62, :_reduce_46,
 4, 58, :_reduce_47,
 4, 58, :_reduce_48,
 0, 58, :_reduce_none,
 1, 63, :_reduce_none,
 1, 63, :_reduce_none,
 1, 63, :_reduce_none,
 1, 63, :_reduce_none,
 1, 63, :_reduce_none,
 1, 63, :_reduce_none,
 1, 63, :_reduce_none,
 5, 54, :_reduce_57,
 1, 64, :_reduce_none,
 2, 47, :_reduce_none,
 0, 47, :_reduce_none ]

racc_reduce_n = 61

racc_shift_n = 99

racc_action_table = [
     5,    81,    83,    28,    10,    71,    27,    27,    22,     1,
    55,     5,    31,    24,     5,    29,    81,    83,    10,    43,
    65,    96,    95,     1,    57,    66,    43,    10,    84,    86,
    87,    43,    80,    10,    10,     7,     9,    12,    15,    26,
    10,    18,    79,    84,    86,    87,     7,    80,    10,     7,
     9,    12,    15,    43,     5,    18,    44,    79,    10,     9,
    43,    15,    10,     1,    18,     9,     9,    15,    15,     5,
    18,    18,     9,    43,    15,    51,    43,    18,    49,    44,
     9,    43,    15,    44,    70,    18,    38,    39,    40,     7,
     9,    12,    15,    54,     9,    18,    15,    43,    43,    18,
    43,    43,    32,    78,     7,    52,    15,    89,    43,    91,
    43,    93,    34,    94,    35,    36,    53,    43,    43 ]

racc_action_check = [
     0,    74,    74,     6,     0,    53,     7,     5,     5,     0,
    28,    42,     7,     5,    56,     6,    73,    73,    56,    29,
    42,    92,    92,    56,    30,    42,    34,    14,    74,    74,
    74,    35,    74,     3,    68,     0,     0,     0,     0,     5,
    11,     0,    74,    73,    73,    73,    42,    73,    16,    56,
    56,    56,    56,    36,    37,    56,    17,    73,    37,    14,
    38,    14,     4,    37,    14,     3,    68,     3,    68,    18,
     3,    68,    11,    39,    11,    22,    43,    11,    18,    16,
    16,    44,    16,    46,    51,    16,    13,    13,    13,    37,
    37,    37,    37,    25,     4,    37,     4,    15,    64,     4,
    65,    66,     9,    71,    18,    23,     2,    75,    77,    82,
    85,    88,    13,    90,    13,    13,    24,    95,    96 ]

racc_action_pointer = [
    -2,   nil,    66,    27,    56,    -3,     3,    -4,   nil,    91,
   nil,    34,   nil,    79,    21,    88,    42,    19,    67,   nil,
   nil,   nil,    68,    63,   105,    51,   nil,   nil,    10,    10,
   -18,   nil,   nil,   nil,    17,    22,    44,    52,    51,    64,
   nil,   nil,     9,    67,    72,   nil,    46,   nil,   nil,   nil,
   nil,    68,   nil,    -2,   nil,   nil,    12,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    89,    91,    92,   nil,    28,   nil,
   nil,    87,   nil,    13,    -2,    66,   nil,    99,   nil,   nil,
   nil,   nil,    68,   nil,   nil,   101,   nil,   nil,    70,   nil,
    71,   nil,    11,   nil,   nil,   108,   109,   nil,   nil ]

racc_action_default = [
   -61,   -19,   -12,   -44,   -43,   -61,   -61,   -61,    -2,   -61,
   -46,   -45,   -20,   -17,   -42,   -60,   -37,   -15,   -61,   -13,
   -40,   -39,   -33,   -61,   -28,   -61,   -24,   -29,   -61,   -60,
   -61,   -28,   -18,   -41,   -60,   -60,   -60,   -61,   -60,   -60,
    -6,   -38,   -61,   -60,   -60,    -9,   -36,   -11,   -14,   -35,
   -34,   -61,   -25,   -32,   -26,    99,   -61,   -27,    -5,    -8,
    -7,   -16,    -3,    -4,   -60,   -60,   -60,   -59,   -61,   -10,
   -31,   -61,    -1,   -49,   -49,   -61,   -58,   -60,   -30,   -50,
   -54,   -55,   -61,   -56,   -51,   -60,   -52,   -53,   -61,   -23,
   -61,   -22,   -61,   -21,   -57,   -60,   -60,   -47,   -48 ]

racc_goto_table = [
    42,     8,    20,    21,    47,    48,    50,    23,     6,    30,
    33,    82,    88,    41,    56,    46,    19,    45,    37,    58,
    59,    60,    25,    62,    63,    77,   nil,   nil,    67,    68,
    64,   nil,   nil,   nil,    69,   nil,   nil,   nil,    61,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    73,
    74,    75,   nil,   nil,   nil,   nil,   nil,    72,   nil,   nil,
   nil,   nil,    90,   nil,   nil,   nil,   nil,    76,   nil,   nil,
    92,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    97,    98 ]

racc_goto_check = [
     2,     3,     8,     8,     9,     9,    10,    14,     1,    14,
     8,    13,    13,     8,     2,     8,    11,     7,     4,     2,
     2,     2,    15,     2,     2,    19,   nil,   nil,     2,     2,
    10,   nil,   nil,   nil,     9,   nil,   nil,   nil,     3,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,
     2,     2,   nil,   nil,   nil,   nil,   nil,     3,   nil,   nil,
   nil,   nil,     2,   nil,   nil,   nil,   nil,     8,   nil,   nil,
     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     2,     2 ]

racc_goto_pointer = [
   nil,     8,   -15,     1,     5,   nil,   nil,     1,    -1,   -12,
   -12,    14,   nil,   -62,     2,    17,   nil,   nil,   nil,   -43 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,    13,    16,   nil,    17,   nil,
     2,     3,     4,   nil,   nil,   nil,    11,    14,    85,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :FUNCTION => 2,
 :INCLUDES => 3,
 :DASHMATCH => 4,
 :LBRACE => 5,
 :HASH => 6,
 :PLUS => 7,
 :GREATER => 8,
 :S => 9,
 :STRING => 10,
 :IDENT => 11,
 :COMMA => 12,
 :URI => 13,
 :CDO => 14,
 :CDC => 15,
 :NUMBER => 16,
 :PERCENTAGE => 17,
 :LENGTH => 18,
 :EMS => 19,
 :EXS => 20,
 :ANGLE => 21,
 :TIME => 22,
 :FREQ => 23,
 :IMPORTANT_SYM => 24,
 :IMPORT_SYM => 25,
 :MEDIA_SYM => 26,
 :PAGE_SYM => 27,
 :CHARSET_SYM => 28,
 :DIMENSION => 29,
 :PREFIXMATCH => 30,
 :SUFFIXMATCH => 31,
 :SUBSTRINGMATCH => 32,
 :TILDE => 33,
 :NOT_EQUAL => 34,
 :SLASH => 35,
 :DOUBLESLASH => 36,
 :NOT => 37,
 "." => 38,
 "*" => 39,
 "[" => 40,
 "]" => 41,
 ")" => 42,
 ":" => 43,
 "=" => 44 }

racc_use_result_var = true

racc_nt_base = 45

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'FUNCTION',
'INCLUDES',
'DASHMATCH',
'LBRACE',
'HASH',
'PLUS',
'GREATER',
'S',
'STRING',
'IDENT',
'COMMA',
'URI',
'CDO',
'CDC',
'NUMBER',
'PERCENTAGE',
'LENGTH',
'EMS',
'EXS',
'ANGLE',
'TIME',
'FREQ',
'IMPORTANT_SYM',
'IMPORT_SYM',
'MEDIA_SYM',
'PAGE_SYM',
'CHARSET_SYM',
'DIMENSION',
'PREFIXMATCH',
'SUFFIXMATCH',
'SUBSTRINGMATCH',
'TILDE',
'NOT_EQUAL',
'SLASH',
'DOUBLESLASH',
'NOT',
'"."',
'"*"',
'"["',
'"]"',
'")"',
'":"',
'"="',
'$start',
'selector',
's_0toN',
'simple_selector_1toN',
'combinator',
'simple_selector',
'element_name',
'hcap_0toN',
'hcap_1toN',
'negation',
'function',
'attrib',
'class',
'attrib_val_0or1',
'expr',
'an_plus_b',
'pseudo',
'attribute_id',
'eql_incl_dash',
'negation_arg']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 13
  def _reduce_1( val, _values, result )
        result = [val.first, val.last].flatten
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 13
  def _reduce_2( val, _values, result )
 result = val.flatten
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 16
  def _reduce_3( val, _values, result )
 result = :DIRECT_ADJACENT_SELECTOR
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 17
  def _reduce_4( val, _values, result )
 result = :CHILD_SELECTOR
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 18
  def _reduce_5( val, _values, result )
 result = :PRECEDING_SELECTOR
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 19
  def _reduce_6( val, _values, result )
 result = :DESCENDANT_SELECTOR
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 20
  def _reduce_7( val, _values, result )
 result = :DESCENDANT_SELECTOR
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 21
  def _reduce_8( val, _values, result )
 result = :CHILD_SELECTOR
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 31
  def _reduce_9( val, _values, result )
        result =  if val[1].nil?
                    val.first
                  else
                    Node.new(:CONDITIONAL_SELECTOR, [val.first, val[1]])
                  end
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 39
  def _reduce_10( val, _values, result )
        result = Node.new(:CONDITIONAL_SELECTOR,
          [
            val.first,
            Node.new(:COMBINATOR, [val[1], val.last])
          ]
        )
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 42
  def _reduce_11( val, _values, result )
        result = Node.new(:CONDITIONAL_SELECTOR, val)
   result
  end
.,.,

 # reduce 12 omitted

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 46
  def _reduce_13( val, _values, result )
        result = Node.new(:CONDITIONAL_SELECTOR, val)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 54
  def _reduce_14( val, _values, result )
        result = Node.new(:CONDITIONAL_SELECTOR,
          [
            Node.new(:ELEMENT_NAME, ['*']),
            Node.new(:COMBINATOR, val)
          ]
        )
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 59
  def _reduce_15( val, _values, result )
        result = Node.new(:CONDITIONAL_SELECTOR,
          [Node.new(:ELEMENT_NAME, ['*']), val.first]
        )
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 64
  def _reduce_16( val, _values, result )
        result = Node.new(val[1], [val.first, val.last])
   result
  end
.,.,

 # reduce 17 omitted

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 67
  def _reduce_18( val, _values, result )
 result = Node.new(:CLASS_CONDITION, [val[1]])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 70
  def _reduce_19( val, _values, result )
 result = Node.new(:ELEMENT_NAME, val)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 71
  def _reduce_20( val, _values, result )
 result = Node.new(:ELEMENT_NAME, val)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 79
  def _reduce_21( val, _values, result )
        result = Node.new(:ATTRIBUTE_CONDITION,
          [Node.new(:ELEMENT_NAME, [val[2]])] + (val[4] || [])
        )
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 84
  def _reduce_22( val, _values, result )
        result = Node.new(:ATTRIBUTE_CONDITION,
          [val[2]] + (val[4] || [])
        )
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 90
  def _reduce_23( val, _values, result )
        # Non standard, but hpricot supports it.
        result = Node.new(:PSEUDO_CLASS,
          [Node.new(:FUNCTION, ['nth-child(', val[2]])]
        )
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 95
  def _reduce_24( val, _values, result )
        result = Node.new(:FUNCTION, [val.first.strip])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 98
  def _reduce_25( val, _values, result )
        result = Node.new(:FUNCTION, [val.first.strip, val[1]].flatten)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 101
  def _reduce_26( val, _values, result )
        result = Node.new(:FUNCTION, [val.first.strip, val[1]].flatten)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 104
  def _reduce_27( val, _values, result )
        result = Node.new(:FUNCTION, [val.first.strip, val[1]].flatten)
   result
  end
.,.,

 # reduce 28 omitted

 # reduce 29 omitted

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 118
  def _reduce_30( val, _values, result )
        if val[1] == 'n'
          result = Node.new(:AN_PLUS_B, val)
        else
          raise Racc::ParseError, "parse error on IDENT '#{val[1]}'"
        end
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 129
  def _reduce_31( val, _values, result )
               # n+3, -n+3
        if val[0] == 'n'
          val.unshift("1")
          result = Node.new(:AN_PLUS_B, val)
        elsif val[0] == '-n'
          val[0] = 'n'
          val.unshift("-1")
          result = Node.new(:AN_PLUS_B, val)
        else
          raise Racc::ParseError, "parse error on IDENT '#{val[1]}'"
        end
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 140
  def _reduce_32( val, _values, result )
        if val[1] == 'n'
          val << "+"
          val << "0"
          result = Node.new(:AN_PLUS_B, val)
        else
          raise Racc::ParseError, "parse error on IDENT '#{val[1]}'"
        end
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 152
  def _reduce_33( val, _values, result )
        if val[0] == 'even'
          val = ["2","n","+","0"]
          result = Node.new(:AN_PLUS_B, val)
        elsif val[0] == 'odd'
          val = ["2","n","+","1"]
          result = Node.new(:AN_PLUS_B, val)
        else
          raise Racc::ParseError, "parse error on IDENT '#{val[0]}'"
        end
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 157
  def _reduce_34( val, _values, result )
        result = Node.new(:PSEUDO_CLASS, [val[1]])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 157
  def _reduce_35( val, _values, result )
 result = Node.new(:PSEUDO_CLASS, [val[1]])
   result
  end
.,.,

 # reduce 36 omitted

 # reduce 37 omitted

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 167
  def _reduce_38( val, _values, result )
        result = Node.new(:COMBINATOR, val)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 170
  def _reduce_39( val, _values, result )
        result = Node.new(:COMBINATOR, val)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 173
  def _reduce_40( val, _values, result )
        result = Node.new(:COMBINATOR, val)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 176
  def _reduce_41( val, _values, result )
        result = Node.new(:COMBINATOR, val)
   result
  end
.,.,

 # reduce 42 omitted

 # reduce 43 omitted

 # reduce 44 omitted

 # reduce 45 omitted

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 182
  def _reduce_46( val, _values, result )
 result = Node.new(:ID, val)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 185
  def _reduce_47( val, _values, result )
 result = [val.first, val[2]]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 186
  def _reduce_48( val, _values, result )
 result = [val.first, val[2]]
   result
  end
.,.,

 # reduce 49 omitted

 # reduce 50 omitted

 # reduce 51 omitted

 # reduce 52 omitted

 # reduce 53 omitted

 # reduce 54 omitted

 # reduce 55 omitted

 # reduce 56 omitted

module_eval <<'.,.,', 'lib/nokogiri/css/parser.y', 202
  def _reduce_57( val, _values, result )
        result = Node.new(:NOT, [val[2]])
   result
  end
.,.,

 # reduce 58 omitted

 # reduce 59 omitted

 # reduce 60 omitted

 def _reduce_none( val, _values, result )
  result
 end

    end   # class GeneratedParser

  end   # module CSS

end   # module Nokogiri
