---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  postgresql
  host: localhost
  username: glenn
  database: merbunity_development
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: merbunity_test
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  database: merbunity_production
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults
